# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bingo(object):
    def setupUi(self, Bingo):
        Bingo.setObjectName("Bingo")
        Bingo.resize(1107, 902)
        self.centralwidget = QtWidgets.QWidget(Bingo)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1151, 891))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../OneDrive/Área de Trabalho/IF/Tópicos em Programação/fundo.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 190, 241, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../OneDrive/Área de Trabalho/IF/Tópicos em Programação/bingo2.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 10, 191, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../OneDrive/Área de Trabalho/IF/Tópicos em Programação/bingoo.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 411, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../OneDrive/Área de Trabalho/IF/Tópicos em Programação/letras bingoo.png"))
        self.label_4.setObjectName("label_4")
        self.tabela = QtWidgets.QTableWidget(self.centralwidget)
        self.tabela.setGeometry(QtCore.QRect(10, 280, 461, 561))
        self.tabela.setMaximumSize(QtCore.QSize(15000, 15000))
        self.tabela.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tabela.setShowGrid(False)
        self.tabela.setRowCount(15)
        self.tabela.setColumnCount(5)
        self.tabela.setObjectName("tabela")
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setVerticalHeaderItem(0, item)
        self.tabela.horizontalHeader().setVisible(False)
        self.tabela.horizontalHeader().setDefaultSectionSize(98)
        self.tabela.horizontalHeader().setHighlightSections(False)
        self.tabela.verticalHeader().setVisible(False)
        self.numeros = QtWidgets.QLabel(self.centralwidget)
        self.numeros.setGeometry(QtCore.QRect(830, 430, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.numeros.setFont(font)
        self.numeros.setStyleSheet("QLabel {\n"
"    color: white;\n"
"      text-align: center; \n"
"    \n"
"}")
        self.numeros.setText("")
        self.numeros.setObjectName("numeros")
        self.btSortear = QtWidgets.QPushButton(self.centralwidget)
        self.btSortear.setGeometry(QtCore.QRect(930, 220, 61, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btSortear.setFont(font)
        self.btSortear.setObjectName("btSortear")
        Bingo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Bingo)
        self.statusbar.setObjectName("statusbar")
        Bingo.setStatusBar(self.statusbar)

        self.retranslateUi(Bingo)
        QtCore.QMetaObject.connectSlotsByName(Bingo)

    def retranslateUi(self, Bingo):
        _translate = QtCore.QCoreApplication.translate
        Bingo.setWindowTitle(_translate("Bingo", "MainWindow"))
        item = self.tabela.verticalHeaderItem(0)
        item.setText(_translate("Bingo", "New Row"))
        self.btSortear.setText(_translate("Bingo", "Sortear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bingo = QtWidgets.QMainWindow()
    ui = Ui_Bingo()
    ui.setupUi(Bingo)
    Bingo.show()
    sys.exit(app.exec_())
